spring.application.name=stol-trainer

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:mypassword}

spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:stol_trainer}

server.port=${SERVER_PORT:8290}

jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.name=${APP_NAME:Stol Trainer}
app.version=${APP_VERSION:1.0.0-MVP}
